const Menu = [
  {
    id: 1,
    image: "./images/maggie.jpg",
    foodname: "MAGGIE",
    category: "Breakfast",
    price: "Rs.60",
    description: "Lorem Ipsum is simply dummy text of the printing ",
  },
  {
    id: 2,
    image: "./images/Pav Bhaji.jpg",
    foodname: "PAV BHAJI",
    category: "Lunch",
    price: "Rs.120",
    description: "Lorem Ipsum is simply dummy text of the printing ",
  },
  {
    id: 3,
    image: "./images/Pizza.jpg",
    foodname: "PIZZA",
    category: "Evening",
    price: "Rs.260",
    description: "Lorem Ipsum is simply dummy text of the printing ",
  },
  {
    id: 10,
    image: "./images/Vadapav.jpg",
    foodname: "VADA PAV",
    category: "Evening",
    price: "Rs.20",
    description: "Lorem Ipsum is simply dummy text of the printing ",
  },
  {
    id: 11,
    image: "./images/Ragadapuri.jpg",
    foodname: "RAGADA PURI",
    category: "Lunch",
    price: "Rs.80",
    description: "Lorem Ipsum is simply dummy text of the printing ",
  },
  {
    id: 12,
    image: "./images/Sabudanavada.jpg",
    foodname: "SABUDANA VADA",
    category: "Dinner",
    price: "Rs.70",
    description: "Lorem Ipsum is simply dummy text of the printing ",
  },
  {
    id: 4,
    image: "./images/Burger.jpg",
    foodname: "BURGER",
    category: "Breakfast",
    price: "Rs.150",
    description: "Lorem Ipsum is simply dummy text of the printing ",
  },
  {
    id: 5,
    image: "./images/Paneer.jpg",
    foodname: "PANEER THALI",
    category: "Lunch",
    price: "Rs.220",
    description: "Lorem Ipsum is simply dummy text of the printing ",
  },
  {
    id: 6,
    image: "./images/Samosa.jpg",
    foodname: "SAMOSA",
    category: "Breakfast",
    price: "Rs.20",
    description: "Lorem Ipsum is simply dummy text of the printing ",
  },
];

export default Menu;
